"""Report generation: assemble facts into structured Markdown with citations."""
import re
from datetime import datetime, timezone

from models import ExtractedFact, Citation, ResearchReport, ReportMetadata
from config import config


def _slugify(text: str) -> str:
    """Convert text to URL-safe slug."""
    slug = text.lower().strip()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug[:80]


def _build_citations(facts: list[ExtractedFact]) -> list[Citation]:
    """Build citation index from extracted facts."""
    citations = []
    for i, fact in enumerate(facts, 1):
        # Extract a highlight anchor: use a short key phrase from the quoted text
        highlight = fact.quoted_text[:100] if fact.quoted_text else fact.fact[:100]
        citations.append(Citation(
            index=i,
            source_name=fact.source_title,
            source_url=fact.source_url,
            quoted_text=fact.quoted_text,
            highlight_anchor=highlight.strip(),
        ))
    return citations


def _generate_markdown(
    topic: str,
    facts: list[ExtractedFact],
    citations: list[Citation],
    started_at: datetime,
    completed_at: datetime,
) -> str:
    """Generate structured Markdown report with citation markers."""

    # Group facts by confidence
    high = [f for f in facts if f.confidence == "high"]
    medium = [f for f in facts if f.confidence == "medium"]
    low = [f for f in facts if f.confidence == "low"]

    # Build index map: fact -> 1-based citation index (avoids bugs with duplicate facts)
    fact_index_map = {id(f): i + 1 for i, f in enumerate(facts)}

    lines = [
        f"# Research Report: {topic}",
        "",
        f"*Generated: {completed_at.strftime('%Y-%m-%d %H:%M UTC')}*",
        f"*Sources: {len(facts)} facts from {len(set(f.source_url for f in facts))} unique URLs*",
        "",
        "---",
        "",
        "## Key Findings",
        "",
    ]

    # High confidence first
    if high:
        lines.append("### High Confidence (multi-source or official data)")
        lines.append("")
        for fact in high:
            idx = fact_index_map[id(fact)]
            lines.append(f"- {fact.fact} [^{idx}]")
        lines.append("")

    if medium:
        lines.append("### Medium Confidence")
        lines.append("")
        for fact in medium:
            idx = fact_index_map[id(fact)]
            lines.append(f"- {fact.fact} [^{idx}]")
        lines.append("")

    if low:
        lines.append("### Low Confidence (single source or implied)")
        lines.append("")
        for fact in low:
            idx = fact_index_map[id(fact)]
            lines.append(f"- {fact.fact} [^{idx}]")
        lines.append("")

    # Sources section
    lines.extend([
        "---",
        "",
        "## Sources",
        "",
    ])
    for c in citations:
        lines.append(f"[^{c.index}]: [{c.source_name}]({c.source_url}) — *\"{c.quoted_text[:120]}{'...' if len(c.quoted_text) > 120 else ''}\"*")
        lines.append("")

    lines.extend([
        "---",
        "",
        "*This report was generated by Search Agent. Verify important claims against original sources.*",
    ])

    return "\n".join(lines)


def generate_report(
    topic: str,
    facts: list[ExtractedFact],
    started_at: datetime = None,
) -> ResearchReport:
    """Generate a complete ResearchReport from extracted facts."""
    now = datetime.now(timezone.utc)
    if started_at is None:
        started_at = now

    slug = _slugify(topic)
    if not slug:
        slug = f"research-{now.strftime('%Y%m%d-%H%M%S')}"

    citations = _build_citations(facts)
    markdown = _generate_markdown(topic, facts, citations, started_at, now)

    unique_urls = set(f.source_url for f in facts)
    metadata = ReportMetadata(
        execution_time_seconds=(now - started_at).total_seconds(),
        source_count=len(unique_urls),
        topics_searched=[topic],
        started_at=started_at.isoformat(),
        completed_at=now.isoformat(),
    )

    return ResearchReport(
        topic=topic,
        slug=slug,
        facts=facts,
        citations=citations,
        markdown=markdown,
        metadata=metadata,
    )
