"""Report generation: assemble facts into structured Markdown with citations."""
import re
from datetime import datetime, timezone

from models import (
    ExtractedFact,
    Citation,
    ResearchReport,
    ReportMetadata,
    ReportSynthesis,
    SearchResult,
)
from report_synthesis import fallback_synthesis
from source_snapshots import build_source_snapshots


def _slugify(text: str, now: datetime) -> str:
    """Convert text to URL-safe slug with timestamp suffix."""
    slug = text.lower().strip()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    if not slug:
        slug = "research"
    slug = slug[:60]
    return f"{slug}-{now.strftime('%Y%m%d-%H%M%S')}"


def _build_citations(facts: list[ExtractedFact]) -> list[Citation]:
    """Build citation index from extracted facts."""
    citations = []
    for i, fact in enumerate(facts, 1):
        highlight = fact.quoted_text[:100] if fact.quoted_text else fact.fact[:100]
        citations.append(Citation(
            index=i,
            source_name=fact.source_title,
            source_url=fact.source_url,
            quoted_text=fact.quoted_text,
            highlight_anchor=highlight.strip(),
        ))
    return citations


def _findings_table_markdown(synthesis: ReportSynthesis) -> list[str]:
    lines = [
        "## Structured Findings",
        "",
        "| Entity | Signal | Date | Confidence | Ref |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in synthesis.structured_findings:
        entity = row.entity.replace("|", "\\|")
        signal = row.signal.replace("|", "\\|")
        date = row.date or "—"
        ref = f"[^{row.citation_index}]" if row.citation_index else "—"
        lines.append(
            f"| {entity} | {signal} | {date} | {row.confidence} | {ref} |"
        )
    lines.append("")
    return lines


def _generate_markdown(
    topic: str,
    facts: list[ExtractedFact],
    citations: list[Citation],
    synthesis: ReportSynthesis,
    started_at: datetime,
    completed_at: datetime,
) -> str:
    """Generate structured Markdown report with synthesis, table, and citations."""
    high = [f for f in facts if f.confidence == "high"]
    medium = [f for f in facts if f.confidence == "medium"]
    low = [f for f in facts if f.confidence == "low"]
    fact_index_map = {id(f): i + 1 for i, f in enumerate(facts)}

    lines = [
        f"# Intelligence Brief: {topic}",
        "",
        f"*Generated: {completed_at.strftime('%Y-%m-%d %H:%M UTC')}*",
        f"*Sources: {len(facts)} facts from {len(set(f.source_url for f in facts))} unique URLs*",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        synthesis.executive_summary,
        "",
        "---",
        "",
    ]

    if synthesis.structured_findings:
        lines.extend(_findings_table_markdown(synthesis))
        lines.extend(["---", ""])

    lines.extend(["## Key Findings", ""])

    if high:
        lines.append("### High Confidence")
        lines.append("")
        for fact in high:
            idx = fact_index_map[id(fact)]
            lines.append(f"- {fact.fact} [^{idx}]")
        lines.append("")

    if medium:
        lines.append("### Medium Confidence")
        lines.append("")
        for fact in medium:
            idx = fact_index_map[id(fact)]
            lines.append(f"- {fact.fact} [^{idx}]")
        lines.append("")

    if low:
        lines.append("### Low Confidence")
        lines.append("")
        for fact in low:
            idx = fact_index_map[id(fact)]
            lines.append(f"- {fact.fact} [^{idx}]")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## Coverage & Gaps",
        "",
        "### Coverage",
        "",
        synthesis.coverage or "_No coverage notes._",
        "",
        "### Gaps",
        "",
        synthesis.gaps or "_No gap analysis._",
        "",
        "---",
        "",
        "## Sources",
        "",
    ])
    for c in citations:
        quote = c.quoted_text[:120] + ("..." if len(c.quoted_text) > 120 else "")
        lines.append(f"[^{c.index}]: [{c.source_name}]({c.source_url}) — *\"{quote}\"*")
        lines.append("")

    lines.extend([
        "---",
        "",
        "*Generated by Search Agent. Verify important claims against original sources.*",
    ])

    return "\n".join(lines)


def generate_report(
    topic: str,
    facts: list[ExtractedFact],
    started_at: datetime = None,
    synthesis: ReportSynthesis | None = None,
    topics_searched: list[str] | None = None,
    fetched_results: list[SearchResult] | None = None,
) -> ResearchReport:
    """Generate a complete ResearchReport from extracted facts."""
    now = datetime.now(timezone.utc)
    if started_at is None:
        started_at = now

    searched = topics_searched or [topic]
    if synthesis is None:
        synthesis = fallback_synthesis(topic, facts, searched)

    slug = _slugify(topic, now)
    citations = _build_citations(facts)
    markdown = _generate_markdown(topic, facts, citations, synthesis, started_at, now)

    unique_urls = set(f.source_url for f in facts)
    metadata = ReportMetadata(
        execution_time_seconds=(now - started_at).total_seconds(),
        source_count=len(unique_urls),
        topics_searched=searched,
        started_at=started_at.isoformat(),
        completed_at=now.isoformat(),
    )

    snapshots = build_source_snapshots(fetched_results or [])

    return ResearchReport(
        topic=topic,
        slug=slug,
        facts=facts,
        citations=citations,
        markdown=markdown,
        summary=synthesis.executive_summary,
        structured_findings=synthesis.structured_findings,
        coverage=synthesis.coverage,
        gaps=synthesis.gaps,
        source_snapshots=snapshots,
        metadata=metadata,
    )
